# Generated by Django 5.2.4 on 2025-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi')], default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi')], default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi')], default='NGN', max_length=10),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='default_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi')], default='NGN', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi')], default='NGN', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi')], default='NGN', max_length=10),
        ),
    ]
